//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcedamicInfo
    {
        public int courseID { get; set; }
        public string courseName { get; set; }
        public string batch { get; set; }
        public Nullable<int> universityID { get; set; }
        public Nullable<int> facultyID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> adminID { get; set; }
        public int yearID { get; set; }
        public Nullable<int> yearNumber { get; set; }
        public int semesterID { get; set; }
        public Nullable<int> semesterNumber { get; set; }
        public string moduleCode { get; set; }
        public string lecturerName { get; set; }
        public string moduleName { get; set; }
        public string GPA { get; set; }
        public Nullable<int> credits { get; set; }
        public string compulary { get; set; }
    }
}
