//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Enrollments = new HashSet<Enrollment>();
            this.Semester_Module = new HashSet<Semester_Module>();
            this.Module1 = new HashSet<Module>();
            this.Modules = new HashSet<Module>();
        }
    
        public string moduleCode { get; set; }
        public string name { get; set; }
        public string GPA { get; set; }
        public Nullable<int> credits { get; set; }
        public string compulary { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Semester_Module> Semester_Module { get; set; }
        public virtual ICollection<Module> Module1 { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
    }
}
