//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultMapping
    {
        public ResultMapping()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public string result { get; set; }
        public Nullable<double> GPA { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
