//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        public Semester()
        {
            this.Semester_Module = new HashSet<Semester_Module>();
        }
    
        public int semesterID { get; set; }
        public Nullable<int> yearID { get; set; }
        public Nullable<int> semesterNumber { get; set; }
    
        public virtual AcedemicYear AcedemicYear { get; set; }
        public virtual ICollection<Semester_Module> Semester_Module { get; set; }
    }
}
