//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceAnalyzer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester_Module
    {
        public int semesterID { get; set; }
        public string moduleCode { get; set; }
        public string lecturerName { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
