// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Success scenario
        /// </summary>
        public void adminLogin()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uIGradePerformanceAnalDocument = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow.UIGradePerformanceAnalDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            WinButton uIItemButton = this.UIItemWindow.UIItemComboBox.UIItemButton;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(682, 250));

            // Type 'a' in 'Grade Performance Analyzer - Google Chrome' document
            Keyboard.SendKeys(uIGradePerformanceAnalDocument, this.adminLoginParams.UIGradePerformanceAnalDocumentSendKeys, ModifierKeys.None);

            // Type 'dmin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.adminLoginParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(646, 353));

            // Type 'admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.adminLoginParams.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(774, 431));

            // Click button
            Mouse.Click(uIItemButton, new Point(26, 17));
        }
        
        /// <summary>
        /// checking url
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UIGradePerformanceAnalWindow.UIItemGroup.UIAddressandsearchbarEdit;
            #endregion

            // Verify that the 'Text' property of 'Address and search bar' text box equals 'localhost:41826/PresentationLayer/Admin/Home.aspx'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIAddressandsearchbarEditText, uIAddressandsearchbarEdit.Text, "Login unsuccessful");
        }
        
        /// <summary>
        /// unsuccessful scenario
        /// </summary>
        public void adminLogin2()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowClient;
            WinClient uIChromeLegacyWindowClient1 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow2.UIChromeLegacyWindowClient;
            WinControl uIGradePerformanceAnalDocument = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow3.UIGradePerformanceAnalDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow4.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument1 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow5.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument2 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow6.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument3 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow7.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(499, 234));

            // Move 'Chrome Legacy Window' client
            Mouse.StartDragging(uIChromeLegacyWindowClient1, new Point(504, 242));
            Mouse.StopDragging(uIChromeLegacyWindowClient1, -5, 0);

            // Type 'a' in 'Grade Performance Analyzer - Google Chrome' document
            Keyboard.SendKeys(uIGradePerformanceAnalDocument, this.adminLogin2Params.UIGradePerformanceAnalDocumentSendKeys, ModifierKeys.None);

            // Type 'dmin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.adminLogin2Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument1, new Point(497, 345));

            // Type 'ad' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument2, this.adminLogin2Params.UIChromeLegacyWindowDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument3, new Point(790, 432));
        }
        
        /// <summary>
        /// login success
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument1 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument1;
            WinControl uIChromeLegacyWindowDocument2 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument2;
            WinControl uIChromeLegacyWindowDocument3 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument3;
            WinControl uIChromeLegacyWindowDocument4 = this.UIGradePerformanceAnalWindow.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument4;
            WinButton uIItemButton = this.UIItemWindow.UIItemComboBox.UIItemButton;
            #endregion

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(524, 243));

            // Type 'admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument1, this.RecordedMethod1Params.UIChromeLegacyWindowDocument1SendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument2, new Point(714, 354));

            // Type 'admin' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument3, this.RecordedMethod1Params.UIChromeLegacyWindowDocument3SendKeys, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument4, new Point(744, 424));

            // Click button
            Mouse.Click(uIItemButton, new Point(20, 19));
        }
        
        /// <summary>
        /// success login
        /// </summary>
        public void AssertMethod2()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UIGradePerformanceAnalWindow.UIItemGroup.UIAddressandsearchbarEdit;
            #endregion

            // Verify that the 'Text' property of 'Address and search bar' text box equals 'localhost:41826/PresentationLayer/Admin/Home.aspx'
            Assert.AreEqual(this.AssertMethod2ExpectedValues.UIAddressandsearchbarEditText, uIAddressandsearchbarEdit.Text, "logn fail");
        }
        
        /// <summary>
        /// gmailLogin
        /// </summary>
        public void gmailLogin()
        {
            #region Variable Declarations
            WinButton uINewTabButton = this.UIMystartsearchGoogleCWindow.UIItemTabList.UINewTabButton;
            WinGroup uIItemGroup = this.UIMystartsearchGoogleCWindow.UIMainToolBar.UIItemGroup;
            WinEdit uIAddressandsearchbarEdit = this.UIMystartsearchGoogleCWindow.UIItemGroup.UIAddressandsearchbarEdit;
            #endregion

            // Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe' with arguments '--no-startup-window'
            ApplicationUnderTest uIMystartsearchGoogleCWindow = ApplicationUnderTest.Launch(this.gmailLoginParams.UIMystartsearchGoogleCWindowExePath, this.gmailLoginParams.UIMystartsearchGoogleCWindowAlternateExePath, "--no-startup-window");

            // Click 'New Tab' button
            Mouse.Click(uINewTabButton, new Point(18, 16));

            // Click group
            Mouse.Click(uIItemGroup, new Point(133, 27));

            // Click 'Address and search bar' text box
            Mouse.Click(uIAddressandsearchbarEdit, new Point(106, 15));

            // Type 'gmail.com{Enter}' in 'Address and search bar' text box
            Keyboard.SendKeys(uIAddressandsearchbarEdit, this.gmailLoginParams.UIAddressandsearchbarEditSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// AssertMethodgmailLogin - Use 'AssertMethodgmailLoginExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethodgmailLogin()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchbarEdit = this.UIMystartsearchGoogleCWindow.UIItemGroup.UIAddressandsearchbarEdit;
            #endregion

            // Verify that the 'Text' property of 'Address and search bar' text box equals 'https://mail.google.com/mail/u/0/#inbox'
            Assert.AreEqual(this.AssertMethodgmailLoginExpectedValues.UIAddressandsearchbarEditText, uIAddressandsearchbarEdit.Text);
        }
        
        #region Properties
        public virtual adminLoginParams adminLoginParams
        {
            get
            {
                if ((this.madminLoginParams == null))
                {
                    this.madminLoginParams = new adminLoginParams();
                }
                return this.madminLoginParams;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual adminLogin2Params adminLogin2Params
        {
            get
            {
                if ((this.madminLogin2Params == null))
                {
                    this.madminLogin2Params = new adminLogin2Params();
                }
                return this.madminLogin2Params;
            }
        }
        
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public virtual AssertMethod2ExpectedValues AssertMethod2ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod2ExpectedValues == null))
                {
                    this.mAssertMethod2ExpectedValues = new AssertMethod2ExpectedValues();
                }
                return this.mAssertMethod2ExpectedValues;
            }
        }
        
        public virtual gmailLoginParams gmailLoginParams
        {
            get
            {
                if ((this.mgmailLoginParams == null))
                {
                    this.mgmailLoginParams = new gmailLoginParams();
                }
                return this.mgmailLoginParams;
            }
        }
        
        public virtual AssertMethodgmailLoginExpectedValues AssertMethodgmailLoginExpectedValues
        {
            get
            {
                if ((this.mAssertMethodgmailLoginExpectedValues == null))
                {
                    this.mAssertMethodgmailLoginExpectedValues = new AssertMethodgmailLoginExpectedValues();
                }
                return this.mAssertMethodgmailLoginExpectedValues;
            }
        }
        
        public UIGradePerformanceAnalWindow UIGradePerformanceAnalWindow
        {
            get
            {
                if ((this.mUIGradePerformanceAnalWindow == null))
                {
                    this.mUIGradePerformanceAnalWindow = new UIGradePerformanceAnalWindow();
                }
                return this.mUIGradePerformanceAnalWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIMystartsearchGoogleCWindow UIMystartsearchGoogleCWindow
        {
            get
            {
                if ((this.mUIMystartsearchGoogleCWindow == null))
                {
                    this.mUIMystartsearchGoogleCWindow = new UIMystartsearchGoogleCWindow();
                }
                return this.mUIMystartsearchGoogleCWindow;
            }
        }
        #endregion
        
        #region Fields
        private adminLoginParams madminLoginParams;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private adminLogin2Params madminLogin2Params;
        
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private AssertMethod2ExpectedValues mAssertMethod2ExpectedValues;
        
        private gmailLoginParams mgmailLoginParams;
        
        private AssertMethodgmailLoginExpectedValues mAssertMethodgmailLoginExpectedValues;
        
        private UIGradePerformanceAnalWindow mUIGradePerformanceAnalWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIMystartsearchGoogleCWindow mUIMystartsearchGoogleCWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'adminLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class adminLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'a' in 'Grade Performance Analyzer - Google Chrome' document
        /// </summary>
        public string UIGradePerformanceAnalDocumentSendKeys = "a";
        
        /// <summary>
        /// Type 'dmin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "dmin";
        
        /// <summary>
        /// Type 'admin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "admin";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Address and search bar' text box equals 'localhost:41826/PresentationLayer/Admin/Home.aspx'
        /// </summary>
        public string UIAddressandsearchbarEditText = "localhost:41826/PresentationLayer/Admin/Home.aspx";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'adminLogin2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class adminLogin2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'a' in 'Grade Performance Analyzer - Google Chrome' document
        /// </summary>
        public string UIGradePerformanceAnalDocumentSendKeys = "a";
        
        /// <summary>
        /// Type 'dmin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "dmin";
        
        /// <summary>
        /// Type 'ad' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "ad";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocument1SendKeys = "admin";
        
        /// <summary>
        /// Type 'admin' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocument3SendKeys = "admin";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethod2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Address and search bar' text box equals 'localhost:41826/PresentationLayer/Admin/Home.aspx'
        /// </summary>
        public string UIAddressandsearchbarEditText = "localhost:41826/PresentationLayer/Admin/Home.aspx";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'gmailLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class gmailLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe' with arguments '--no-startup-window'
        /// </summary>
        public string UIMystartsearchGoogleCWindowExePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles%\Google\Chrome\Application\chrome.exe' with arguments '--no-startup-window'
        /// </summary>
        public string UIMystartsearchGoogleCWindowAlternateExePath = "%ProgramFiles%\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Type 'gmail.com{Enter}' in 'Address and search bar' text box
        /// </summary>
        public string UIAddressandsearchbarEditSendKeys = "gmail.com{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethodgmailLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethodgmailLoginExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of 'Address and search bar' text box equals 'https://mail.google.com/mail/u/0/#inbox'
        /// </summary>
        public string UIAddressandsearchbarEditText = "https://mail.google.com/mail/u/0/#inbox";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIGradePerformanceAnalWindow : WinWindow
    {
        
        public UIGradePerformanceAnalWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Grade Performance Analyzer - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            this.WindowTitles.Add("localhost:41826/PresentationLayer/Admin/Home.aspx - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow2 UIChromeLegacyWindowWindow2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow2 == null))
                {
                    this.mUIChromeLegacyWindowWindow2 = new UIChromeLegacyWindowWindow2(this);
                }
                return this.mUIChromeLegacyWindowWindow2;
            }
        }
        
        public UIChromeLegacyWindowWindow3 UIChromeLegacyWindowWindow3
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow3 == null))
                {
                    this.mUIChromeLegacyWindowWindow3 = new UIChromeLegacyWindowWindow3(this);
                }
                return this.mUIChromeLegacyWindowWindow3;
            }
        }
        
        public UIChromeLegacyWindowWindow4 UIChromeLegacyWindowWindow4
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow4 == null))
                {
                    this.mUIChromeLegacyWindowWindow4 = new UIChromeLegacyWindowWindow4(this);
                }
                return this.mUIChromeLegacyWindowWindow4;
            }
        }
        
        public UIChromeLegacyWindowWindow5 UIChromeLegacyWindowWindow5
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow5 == null))
                {
                    this.mUIChromeLegacyWindowWindow5 = new UIChromeLegacyWindowWindow5(this);
                }
                return this.mUIChromeLegacyWindowWindow5;
            }
        }
        
        public UIChromeLegacyWindowWindow6 UIChromeLegacyWindowWindow6
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow6 == null))
                {
                    this.mUIChromeLegacyWindowWindow6 = new UIChromeLegacyWindowWindow6(this);
                }
                return this.mUIChromeLegacyWindowWindow6;
            }
        }
        
        public UIChromeLegacyWindowWindow7 UIChromeLegacyWindowWindow7
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow7 == null))
                {
                    this.mUIChromeLegacyWindowWindow7 = new UIChromeLegacyWindowWindow7(this);
                }
                return this.mUIChromeLegacyWindowWindow7;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIItemGroup mUIItemGroup;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        
        private UIChromeLegacyWindowWindow2 mUIChromeLegacyWindowWindow2;
        
        private UIChromeLegacyWindowWindow3 mUIChromeLegacyWindowWindow3;
        
        private UIChromeLegacyWindowWindow4 mUIChromeLegacyWindowWindow4;
        
        private UIChromeLegacyWindowWindow5 mUIChromeLegacyWindowWindow5;
        
        private UIChromeLegacyWindowWindow6 mUIChromeLegacyWindowWindow6;
        
        private UIChromeLegacyWindowWindow7 mUIChromeLegacyWindowWindow7;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "225531888";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        
        public WinControl UIGradePerformanceAnalDocument
        {
            get
            {
                if ((this.mUIGradePerformanceAnalDocument == null))
                {
                    this.mUIGradePerformanceAnalDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIGradePerformanceAnalDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIGradePerformanceAnalDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIGradePerformanceAnalDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        
        private WinControl mUIGradePerformanceAnalDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("localhost:41826/PresentationLayer/Admin/Home.aspx - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("localhost:41826/PresentationLayer/Admin/Home.aspx - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument1 == null))
                {
                    this.mUIChromeLegacyWindowDocument1 = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument1.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument1.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument1;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument2
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument2 == null))
                {
                    this.mUIChromeLegacyWindowDocument2 = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument2.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument2.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument2;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument3
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument3 == null))
                {
                    this.mUIChromeLegacyWindowDocument3 = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument3.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument3.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument3;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument4
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument4 == null))
                {
                    this.mUIChromeLegacyWindowDocument4 = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument4.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument4.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument4;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        
        private WinControl mUIChromeLegacyWindowDocument;
        
        private WinControl mUIChromeLegacyWindowDocument1;
        
        private WinControl mUIChromeLegacyWindowDocument2;
        
        private WinControl mUIChromeLegacyWindowDocument3;
        
        private WinControl mUIChromeLegacyWindowDocument4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow2 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow3 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIGradePerformanceAnalDocument
        {
            get
            {
                if ((this.mUIGradePerformanceAnalDocument == null))
                {
                    this.mUIGradePerformanceAnalDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIGradePerformanceAnalDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIGradePerformanceAnalDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIGradePerformanceAnalDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIGradePerformanceAnalDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow4 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow5 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow6 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIChromeLegacyWindowWindow7 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "215372608";
            this.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Grade Performance Analyzer - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private UIItemComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMystartsearchGoogleCWindow : WinWindow
    {
        
        public UIMystartsearchGoogleCWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "mystartsearch - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("mystartsearch - Google Chrome");
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIMainToolBar UIMainToolBar
        {
            get
            {
                if ((this.mUIMainToolBar == null))
                {
                    this.mUIMainToolBar = new UIMainToolBar(this);
                }
                return this.mUIMainToolBar;
            }
        }
        
        public UIItemGroup1 UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup1(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        
        private UIMainToolBar mUIMainToolBar;
        
        private UIItemGroup1 mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("mystartsearch - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinButton UINewTabButton
        {
            get
            {
                if ((this.mUINewTabButton == null))
                {
                    this.mUINewTabButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINewTabButton.SearchProperties[WinButton.PropertyNames.Name] = "New Tab";
                    this.mUINewTabButton.WindowTitles.Add("mystartsearch - Google Chrome");
                    #endregion
                }
                return this.mUINewTabButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINewTabButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMainToolBar : WinToolBar
    {
        
        public UIMainToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "main";
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIItemGroup.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIItemGroup1 : WinGroup
    {
        
        public UIItemGroup1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New Tab - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchbarEdit
        {
            get
            {
                if ((this.mUIAddressandsearchbarEdit == null))
                {
                    this.mUIAddressandsearchbarEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchbarEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search bar";
                    this.mUIAddressandsearchbarEdit.WindowTitles.Add("New Tab - Google Chrome");
                    #endregion
                }
                return this.mUIAddressandsearchbarEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchbarEdit;
        #endregion
    }
}
